"""
Parses campaign data files generated by the PWCG (Pat Wilson's Campaign Generator).

This module defines the file structure and provides a parser to read and load
campaign data from JSON files into a structured dictionary.
"""
from __future__ import annotations
import json
from pathlib import Path
from typing import Dict, List, Any, Optional

class PWCGFileNames:
    """
    A container for constant file and directory names used by PWCG.
    """
    CAMPAIGN = "Campaign.json"
    ACES = "CampaignAces.json"
    LOG = "CampaignLog.json"
    PILOT_EXTRA = "pilot_extra.json"
    DECORATIONS = "decorations.json"
    MISSION_DATA_DIR = "MissionData"
    COMBAT_REPORTS_DIR = "CombatReports"
    MISSION_DATA_PATTERN = "*.MissionData.json"
    COMBAT_REPORT_PATTERN = "*.CombatReport.json"

class IL2DataParser:
    """
    Parses PWCG campaign data from a given root directory.
    """
    def __init__(self, pwcg_root: str | Path) -> None:
        """
        Initialize the parser with the root directory of the PWCG installation.

        Args:
            pwcg_root (str | Path): The path to the PWCG root directory.
        """
        self.base_path = Path(pwcg_root) / "User" / "Campaigns"

    def get_campaigns(self) -> List[str]:
        """
        Get a list of all available campaign names.

        Returns:
            List[str]: A list of campaign directory names.
        """
        if not self.base_path.exists():
            return []
        return [d.name for d in self.base_path.iterdir() if d.is_dir()]

    def _safe_load_json(self, path: Path) -> Any:
        """
        Safely load a JSON file, returning an empty dict on error.

        Args:
            path (Path): The path to the JSON file.

        Returns:
            Any: The loaded JSON data, or an empty dictionary if loading fails.
        """
        if not path.exists():
            return {}
        try:
            with path.open(encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            return {}

    def _load_many_json(self, paths: List[Path]) -> List[Any]:
        """
        Load multiple JSON files from a list of paths.

        Args:
            paths (List[Path]): A list of paths to JSON files.

        Returns:
            List[Any]: A list of loaded JSON data objects.
        """
        out: List[Any] = []
        for p in paths:
            try:
                with p.open(encoding="utf-8") as f:
                    out.append(json.load(f))
            except Exception:
                continue
        return out

    def parse_campaign_json(self, campaign_name: str) -> Optional[Dict[str, Any]]:
        """
        Parse all relevant JSON files for a given campaign.

        Args:
            campaign_name (str): The name of the campaign to parse.

        Returns:
            Optional[Dict[str, Any]]: A dictionary containing all parsed
                                      campaign data, or None if the campaign
                                      directory does not exist.
        """
        campaign_dir = self.base_path / campaign_name
        if not campaign_dir.exists():
            return None
        campaign = self._safe_load_json(campaign_dir / PWCGFileNames.CAMPAIGN)
        aces = self._safe_load_json(campaign_dir / PWCGFileNames.ACES)
        log = self._safe_load_json(campaign_dir / PWCGFileNames.LOG)
        pilot_extra = self._safe_load_json(campaign_dir / PWCGFileNames.PILOT_EXTRA)
        decorations = self._safe_load_json(campaign_dir / PWCGFileNames.DECORATIONS)
        mission_dir = campaign_dir / PWCGFileNames.MISSION_DATA_DIR
        mission_files = list(mission_dir.glob(PWCGFileNames.MISSION_DATA_PATTERN)) if mission_dir.exists() else []
        missions = self._load_many_json(sorted(mission_files))
        combat_dir = campaign_dir / PWCGFileNames.COMBAT_REPORTS_DIR
        combat_files: List[Path] = []
        if combat_dir.exists():
            combat_files.extend(combat_dir.glob(PWCGFileNames.COMBAT_REPORT_PATTERN))
            for sub in combat_dir.iterdir():
                if sub.is_dir():
                    combat_files.extend(sub.glob(PWCGFileNames.COMBAT_REPORT_PATTERN))
        combat_reports = self._load_many_json(sorted(combat_files))
        return {
            "campaign": campaign,
            "aces": aces,
            "log": log,
            "pilot_extra": pilot_extra,
            "decorations": decorations,
            "missions": missions,
            "combat_reports": combat_reports,
            "campaign_name": campaign_name,
            "campaign_path": str(campaign_dir),
        }
